### PR TITLE
fix: make scoop write .json when --skip-publish

### LINKED ISSUE #2374: [Bug]: Scoop pipeline does not write out .json file with --skip-publish
### What happened?

When having a valid scoop config in the .gorelease.yml and running `goreleaser release --skip-publish` it should write the <project>.json file to the dist/ folder but not publish it. This is how the homebrew pipeline works and should be consistent with the --skip-publish flag according to the docs (user is resposible for publishing the produced files).

### How can we reproduce this?

Run `goreleaser release --skip-publish` in the goreleaser (this repo:s) top folder. A goreleaser.json is not written to the dist/ folder.

### goreleaser version

```bash
goreleaser version dev
module version: v0.174.1, checksum: h1:els5gB5csBDQbgx0zVoIaEAKWGebc8Lu1kUH4yibMzs=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

It's a simple deletion of three lines on https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/scoop/scoop.go#L37 - I'd be happy to submit a fix if this is a valid error

### PR DESCRIPTION
**Pull request by jonaslu**
Don't skip the pipeline altogether but write
out the manifest.json file as the homebrew
pipeline does, only skip committing to the repo.

closes #2374

### CODE REVIEW

File: internal/pipe/scoop/scoop_test.go [hunk 1]
```diff
@@ -1051,6 +1059,23 @@ func TestRunPipeScoopWithSkip(t *testing.T) {
...
+	f, err := os.Create(path)
+	require.NoError(t, err)
+	require.NoError(t, f.Close())
+
+	cli := &DummyClient{}
+	require.EqualError(t, doRun(ctx, cli), pipe.ErrSkipPublishEnabled.Error())
+
+	distFile := filepath.Join(folder, ctx.Config.Scoop.Name+".json")
+	_, err = os.Stat(distFile)
+	require.NoError(t, err, "file should exist: "+distFile)
```
Comment (caarlos0) [inline internal/pipe/scoop/scoop_test.go:1076]: can use [`require.FileExists`](https://pkg.go.dev/github.com/stretchr/testify@v1.7.0/require#FileExists)

```suggestion
	require. FileExists(t, distFile)
```

**Review by caarlos0 — APPROVED** [review]

**Comment by caarlos0** [comment]
thanks for the PR :)
