### PR TITLE
fix: signature template failed silently after signing process completed

### LINKED ISSUE #5147: Custom signature template in `binary_signs` leads to release upload failure
### What happened?

I'm trying to get cosign working via goreleaser. Mostly it's been straightforward (and pretty neat actually).

I'm not sure if this is a problem that I've caused or a problem with GoReleaser.

When creating the release, the signing process is called, showing the expected `signature` name being passed in:

```
signing cmd=./ci-only.sh artifact=chinmina-bridge signature=dist/release_linux_amd64_v1/chinmina-bridge_linux_amd64.cosign.bundle
```
[ref](https://github.com/jamestelfer/chinmina-bridge/actions/runs/10971683689/job/30467096527#step:6:187)

After the signing process completes, it indicates the addition of the signature artifact:

```
added new artifact name=chinmina-bridge_ type=Signature path=dist/release_linux_amd64_v1/chinmina-bridge_linux_amd64.cosign.bundle
```
[ref](https://github.com/jamestelfer/chinmina-bridge/actions/runs/10971683689/job/30467096527#step:6:286)

Note the `name=chinmina-bridge_` there.

When the release uploads occur, there are two signatures (one per arch), but they both have the same `name`, resulting in errors.

```
      • uploading to release                         file=dist/release_linux_amd64_v1/chinmina-bridge_linux_amd64.cosign.bundle name=chinmina-bridge_
      • uploading to release                         file=dist/release_linux_arm64/chinmina-bridge_linux_arm64.cosign.bundle name=chinmina-bridge_
      • uploading to release                         file=dist/checksums.txt name=checksums.txt
      • upload failed                                request-id=4143:58730:F8FD43:10F5ACC:66EE9A4B error=POST https://uploads.github.com/repos/jamestelfer/chinmina-bridge/releases/176226441/assets?name=chinmina-bridge_: 404 Not Found [] name=chinmina-bridge_ release-id=176226441
      • failed to upload artifact, will retry        try=1 artifact=chinmina-bridge_ error=POST https://uploads.github.com/repos/jamestelfer/chinmina-bridge/releases/176226441/assets?name=chinmina-bridge_: 404 Not Found []
      • uploading to release                         file=dist/release_linux_amd64_v1/chinmina-bridge_linux_amd64.cosign.bundle name=chinmina-bridge_
      • upload failed                                request-id=4142:16EE:712634:7CC6D4:66EE9A4B error=POST https://uploads.github.com/repos/jamestelfer/chinmina-bridge/releases/176226441/assets?name=chinmina-bridge_: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] name=chinmina-bridge_ release-id=176226441
      • failed to upload artifact, will retry        try=2 artifact=chinmina-bridge_ error=POST https://uploads.github.com/repos/jamestelfer/chinmina-bridge/releases/176226441/assets?name=chinmina-bridge_: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
  ⨯ release failed after 56s                 error=scm releases: failed to publish artifacts: failed to upload chinmina-bridge_ after 2 tries: POST https://uploads.github.com/repos/jamestelfer/chinmina-bridge/releases/176226441/assets?name=chinmina-bridge_: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```
[ref](https://github.com/jamestelfer/chinmina-bridge/actions/runs/10971683689/job/30467096527#step:6:370)

I did try this without setting the `signature`, but it is defaulted and the release fails if the file can't be found.

My preference would be to include the bundle in the tar.gz, but I don't mind it being separate as well.

### How can we reproduce this?

Failing run: https://github.com/jamestelfer/chinmina-bridge/actions/runs/10971683689/job/30467096527#step:6:15

Git ref: refs/tags/v0.6.1-alpha2 (1aebe98a1f9593d720a580636a60b0b7f02ba3d4)

Configuration: https://github.com/jamestelfer/chinmina-bridge/blob/1aebe98a1f9593d720a580636a60b0b7f02ba3d4/.goreleaser.yaml#L24-L34

If I'm looking at this correctly:

1. Create a simple multi-arch go binary
2. Configure the binary to be signed with cosign
3. Configure the `signature` template to include template variables; e.g. `'${artifact}_{{ .Os }}_{{ .Arch }}.cosign.bundle'`

The result will be two `signature` type files in the release with the `name` equal to the expansion of `${artifact}_`

This will fail on release upload.

### goreleaser version

```bash
v2.3.2

See https://github.com/jamestelfer/chinmina-bridge/actions/runs/10971683689/job/30467096527#step:6:15
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I had a look around and narrowed down here, immediately after the signing call:

https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/sign/sign.go#L257-L270

As far as I can tell, the `name` here isn't evaluating the template properly, and is returning a partial result.

### PR DESCRIPTION
**Pull request by jamestelfer**
The presence of an artifact field in the `signature` or `certificate` template field caused a silent failure in the template when re-applied after the external signing process was called.

This was due to the artifact being presence in the template context before the signing process, but not after. An error here was also ignored.

The fix supplies the artifact to the template context, and also allows a template failure to
fail the overall process.

As far as I can tell, this change aligns behaviour to match existing documentation.

Fixes #5147

### CODE REVIEW

File: internal/pipe/sign/sign_binary_test.go [hunk 1]
```diff
@@ -113,9 +115,9 @@ func TestBinarySign(t *testing.T) {
 		require.NoError(tb, pipe.Default(ctx))
 
 		for i := range ctx.Config.BinarySigns {
-			ctx.Config.BinarySigns[i].Args = append(
-				[]string{"--homedir", keyring},
-				ctx.Config.BinarySigns[i].Args...,
+			ctx.Config.BinarySigns[i].Env = append(
+				ctx.Config.BinarySigns[i].Env,
+				"GNUPGHOME="+keyring,
```
Comment (jamestelfer) [inline internal/pipe/sign/sign_binary_test.go:120]: Setting the GPG home dir as an env variable allows other commands to be used in the test.

**Comment by caarlos0** [comment]
ahh, good catch!

LGTM, if tests pass I'll merge it :)

**Review by caarlos0 — APPROVED** [review]

**Comment by jamestelfer** [comment]
Awesome!

Thanks for such a useful utility!
