### PR TITLE
bugfix: handle mixing of job and normal tokens

### LINKED ISSUE #3399: error updating brew formula file statusCode=403
### What happened?

I created a Personal Access Token under https://gitlab.selfhost.com/-/profile/personal_access_tokens (I also tried Project a project access token created at the brew tap repo)

After publishing `publishing ->  scm releases` it fails:

```
⨯ error updating brew formula file             branch=main err=PUT https://gitlab.selfhost.com/api/v4/projects/buschco/homebrew-tap/repository/files/my-go-program.rb: 403 {message: 403 Forbidden} fileName=my-go-program.rb projectID=buschco/homebrew-tap statusCode=403
  • took: 3s
  ⨯ release failed after 2m29s               error=homebrew tap formula: failed to publish artifacts: PUT https://gitlab.selfhost.com/api/v4/projects/buschco/homebrew-tap/repository/files/my-go-program.rb: 403 {message: 403 Forbidden}
```

Either a GitLab upgrade or a new version of `goreleaser` broke my pipeline

### How can we reproduce this?

.goreleaser.yml
```yml
brews:
  - name: my-go-
    tap:
      owner: buschco
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaser
      email: bot@company.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
```

and this CI file:

```yml
release:
  dependencies:
    - "test"
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - HOMEBREW_TAP_TOKEN="$HOMEBREW_TAP_TOKEN" GITLAB_TOKEN="$CI_JOB_TOKEN" goreleaser release --rm-dist
```

### goreleaser version

```bash
goreleaser version 1.11.4
commit: d19ff6eb1eeca75e2bb3fbeaf473b3d0dc6ffc81
built at: 2022-09-19T00:31:33Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.11.4, checksum: h1:bmXfkrBa6xv3WzzZM7U0QCOmpFAanIm+91tFB4DYUnI=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

- It seems like the Personal Access Token is never used.
image

- GitLab Community Edition [15.2.2](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v15.2.2)

### PR DESCRIPTION
**Pull request by drewstinnett**
If applied, this commit will allow for new GitLab clients to use both ci job tokens and plain tokens (for things like brew publishing where the CI_JOB_TOKEN isn't applicable)

This provides a fix for #3399

---

closes #3399

### CODE REVIEW

File: internal/client/gitlab_test.go [hunk 1]
```diff
@@ -546,3 +546,59 @@ func TestCloseMileston(t *testing.T) {
...
+				},
+			},
+			token:   "real-ci-token",
+			ciToken: "real-ci-token",
+			desc:    "token and CI_JOB_TOKEN match, however UseJobToken is set to false, so return false",
+			want:    false,
+		},
+	}
+	for _, tt := range tests {
+		os.Setenv("CI_JOB_TOKEN", tt.ciToken)
```
Comment (caarlos0) [inline internal/client/gitlab_test.go:599]: can use `t.Setenv`, and then we can remove the unsetenv bellow

File: internal/client/gitlab.go [hunk 2]
```diff
@@ -495,3 +497,27 @@ func (c *gitlabClient) getMilestoneByTitle(repo Repo, title string) (*gitlab.Mil
...
+	// UseJobToken. Older versions of GitLab don't work with this, so we
+	// want to be specific
+	if ctx.Config.GitLabURLs.UseJobToken {
+		// We may be creating a new client with a non-CI_JOB_TOKEN, for
+		// things like Homebrew publishing. We can't use the
+		// CI_JOB_TOKEN there
+		if token != ciToken {
+			return false
+		}
+		return true
```
Comment (caarlos0) [inline internal/client/gitlab.go:520]:
```suggestion
		return token == ciToken
```

File: internal/client/gitlab.go [hunk 3]
```diff
@@ -47,7 +47,9 @@ func NewGitLab(ctx *context.Context, token string) (Client, error) {
 
 	var client *gitlab.Client
 	var err error
-	if ctx.Config.GitLabURLs.UseJobToken {
+	useJobClient := checkUseJobToken(*ctx, token)
+
+	if useJobClient {
```
Comment (caarlos0) [inline internal/client/gitlab.go:52]:
```suggestion
	if checkUseJobToken(*ctx, token) {
```

**Review by caarlos0 — COMMENTED** [review]
minor style stuff, lgtm otherwise!

thanks

**Comment by caarlos0** [comment]
closes https://github.com/goreleaser/goreleaser/issues/3399

File: internal/client/gitlab_test.go (hunk 1 above)
Comment (drewstinnett) [reply internal/client/gitlab_test.go:599]: Nice, I didn't know that was a thing, ty! Will update

File: internal/client/gitlab.go (hunk 2 above)
Comment (drewstinnett) [reply internal/client/gitlab.go:520]: Super nice, will update!

**Comment by drewstinnett** [comment]
Ty for the suggestions, teaching me all sorts of new things, much appreciated!! New code is up now

**Comment by caarlos0** [comment]
> Ty for the suggestions, teaching me all sorts of new things, much appreciated!! New code is up now

thank **you** for the fix! 🙏
