### PR TITLE
fix: retain symlinks added to zip archives

### LINKED ISSUE #3584: symlinks not retained in zip archives
### What happened?

When including explicit symlink `files` in `archives` with `format: zip` the symlinks are not linked properly. The filemode header indicates that it is a link, but the symlink has no target. This contrasts with the default archive format (`tar.gz`) which does properly preserve symlink targets.

### How can we reproduce this?

Consider a minimal project with the following files/links. Note that `a/x` is a symlink to `x` and `a/x2` is a symlink to `a/x`.
```
$ git ls-files | xargs ls -l 
-rw-r--r--  1 orawlings  staff    7 Nov 22 15:42 .gitignore
-rw-r--r--  1 orawlings  staff  115 Nov 22 15:53 .goreleaser.yaml
lrwxr-xr-x  1 orawlings  staff    4 Nov 22 16:04 a/x -> ../x
lrwxr-xr-x  1 orawlings  staff    1 Nov 22 16:04 a/x2 -> x
-rw-r--r--  1 orawlings  staff   21 Nov 22 15:45 go.mod
-rw-r--r--  1 orawlings  staff   29 Nov 22 15:45 main.go
-rw-r--r--  1 orawlings  staff    2 Nov 22 15:32 x
```

With `.goreleaser.yaml` contents:
```
project_name: test
archives:
  - id: zip
    format: zip
    files:
    - a/*
    - x
  - files:
    - a/*
    - x
```

Generate the archives:
```
$ goreleaser release --snapshot --skip-publish
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  • loading environment variables
  • getting and validating git state
    • ignoring errors because this is a snapshot     error=couldn't get current branch: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    • building...                                    commit=none latest tag=v0.0.0
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=0.0.0-SNAPSHOT-none
  • checking distribution directory
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/test_darwin_arm64/test
    • building                                       binary=dist/test_linux_386/test
    • building                                       binary=dist/test_linux_amd64_v1/test
    • building                                       binary=dist/test_linux_arm64/test
    • building                                       binary=dist/test_darwin_amd64_v1/test
    • took: 1s
  • archives
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_linux_amd64.tar.gz
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_darwin_arm64.zip
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.tar.gz
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_linux_386.zip
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_linux_amd64.zip
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_linux_arm64.tar.gz
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.zip
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_linux_386.tar.gz
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_linux_arm64.zip
    • creating                                       archive=dist/test_0.0.0-SNAPSHOT-none_darwin_arm64.tar.gz
  • calculating checksums
  • storing release metadata
    • writing                                        file=dist/artifacts.json
    • writing                                        file=dist/metadata.json
  • release succeeded after 0s
```

When extracting the tar.gz archive, the symlinks remain intact:
```
$ (mkdir thetar && tar -C thetar -xf dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.tar.gz) && ls -lR thetar
total 1640
drwxr-xr-x  4 orawlings  staff     128 Nov 22 16:12 a
-rwxr-xr-x  1 orawlings  staff  833104 Nov 22 16:09 test
-rw-r--r--  1 orawlings  staff       2 Nov 22 15:32 x

thetar/a:
total 0
lrwxr-xr-x  1 orawlings  staff  4 Nov 22 16:04 x -> ../x
lrwxr-xr-x  1 orawlings  staff  1 Nov 22 16:04 x2 -> x
```

But when extracting the zip archive, the symlinks are lost (replaced with zero length regular files).
```
$ (mkdir thezip && cd thezip && unzip ../dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.zip) && ls -lR thezip
Archive:  ../dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.zip
  inflating: a/x                     
  inflating: a/x2                    
  inflating: x                       
  inflating: test                    
total 1640
drwxr-xr-x  4 orawlings  staff     128 Nov 22 16:13 a
-rwxr-xr-x  1 orawlings  staff  833104 Nov 22 16:09 test
-rw-r--r--  1 orawlings  staff       2 Nov 22 15:32 x

thezip/a:
total 0
-rwxr-xr-x  1 orawlings  staff  0 Nov 22 16:04 x
-rwxr-xr-x  1 orawlings  staff  0 Nov 22 16:04 x2
```

### goreleaser version

```bash
goreleaser version dev
goos: darwin
goarch: amd64
module version: v1.13.0, checksum: h1:wg7KX6osE+qm0ydBw/B00LQGqXD7qbGXPNDTyBPe/p4=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by orirawlings**
fixes #3584 

When following the reproduction steps in #3584 I now get the following contents for the zip archive:
```
$ goreleaser --snapshot --skip-publish
...
$ (mkdir thezip && cd thezip && unzip ../dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.zip) && ls -lR thezip
Archive:  ../dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.zip
  inflating: a/x                     -> ../x 
  inflating: a/x2                    -> x 
  inflating: x                       
  inflating: test                    
finishing deferred symbolic links:
  a/x                    -> ../x
  a/x2                   -> x
total 1640
drwxr-xr-x  4 orawlings  staff     128 Nov 22 16:19 a
-rwxr-xr-x  1 orawlings  staff  833104 Nov 22 16:19 test
-rw-r--r--  1 orawlings  staff       2 Nov 22 15:32 x

thezip/a:
total 0
lrwxr-xr-x  1 orawlings  staff  4 Nov 22 16:19 x -> ../x
lrwxr-xr-x  1 orawlings  staff  1 Nov 22 16:19 x2 -> x
```

I'm using goreleaser for a project that packages multiple binaries in zip archives. We also include symlinks within the zip archives to give some of the binaries an alternate (usually shorter) spelling so they are easier to invoke on the command line. 

This brings the zip archive behavior regarding symlinks in line with tar.gz and tar archives.

### CODE REVIEW

File: pkg/archive/zip/zip_test.go [hunk 1]
```diff
@@ -85,6 +86,13 @@ func TestZipFile(t *testing.T) {
 		}
 		if zf.Name == "link.txt" {
 			require.True(t, zf.FileInfo().Mode()&os.ModeSymlink != 0)
+			rc, err := zf.Open()
+			require.NoError(t, err)
+			var content bytes.Buffer
+			_, err = io.Copy(&content, rc)
+			require.NoError(t, err)
+			rc.Close()
+			require.Equal(t, content.String(), "regular.txt")
```
Comment (caarlos0) [inline pkg/archive/zip/zip_test.go:95]: I think here we can merely check that the link points to the expected file, no need to actually check file contents.

checking contents also is not guarantee that the link is correct, as it may point to another file with the same content

File: pkg/archive/zip/zip.go [hunk 2]
```diff
@@ -57,9 +59,17 @@ func (a Archive) Add(f config.File) error {
...
-	if info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
+	if info.IsDir() {
 		return nil
 	}
+	if info.Mode()&os.ModeSymlink != 0 {
+		link, err := os.Readlink(f.Source) // #nosec
+		if err != nil {
+			return fmt.Errorf("%s: %w", f.Source, err)
+		}
+		_, err = w.Write([]byte(filepath.ToSlash(link)))
```
Comment (caarlos0) [inline pkg/archive/zip/zip.go:70]: probably better of using `io.WriteString`

**Review by caarlos0 — COMMENTED** [review]
just a couple of comments, but looking good so far, thank you!

File: pkg/archive/zip/zip_test.go (hunk 1 above)
Comment (orirawlings) [reply pkg/archive/zip/zip_test.go:95]: Sorry, my variable name for the buffer might be confusing things. I am checking the destination of the link here. The destination path for the link is encoded as the contents of the link file in the archive. I'll update the variable name to help clarify this.

**Comment by orirawlings** [comment]
@caarlos0 Thank you for the review! I've updated this PR to address your feedback. Please let me know if there is anything else I should adjust.

File: pkg/archive/zip/zip_test.go (hunk 1 above)
Comment (caarlos0) [reply pkg/archive/zip/zip_test.go]: oh, I totally misread it as well 😂

**Comment by caarlos0** [comment]
Thanks!
